### ISSUE TITLE
Delete volume when deleting pvc 

### ISSUE THREAD

**Issue by krakazyabra** [hpe-storage/co-deployments#220]
Hello. I've deployed [3par-primera-csp](https://github.com/hpe-storage/co-deployments/blob/master/yaml/csi-driver/v1.4.0/3par-primera-csp.yaml) for [1.18 ](https://github.com/hpe-storage/co-deployments/blob/master/yaml/csi-driver/v1.4.0/hpe-csi-k8s-1.18.yaml). 
I've faced with problem: when k8s is deleting pvc, the volume on 3par is not deleting. How to configure StorageClass to delete volume? 
I've checked [documentation](https://scod.hpedev.io/container_storage_provider/hpe_3par_primera/index.html), but fount nothing about this.

On 3par I've created Remote Copy Group, configured replication policy.

my config:
<details><summary>secrets</summary>
<p>

```
apiVersion: v1
stringData:
  serviceName: primera3par-csp-svc
  servicePort: "8080"
  backend: 192.168.1.10
  username: 3paradm
  password: 3pardata
kind: Secret
metadata:
  name: 3par01
  namespace: hpe-storage
type: Opaque
---
apiVersion: v1
stringData:
  serviceName: primera3par-csp-svc
  servicePort: "8080"
  backend: 192.168.1.11
  username: 3paradm
  password: 3pardata
kind: Secret
metadata:
  name: 3par02
  namespace: hpe-storage
type: Opaque
```

</p>
</details>

<details><summary>StorageClass</summary>
<p>

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: 3par-1
provisioner: csi.hpe.com
parameters:
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: 3par02
  csi.storage.k8s.io/provisioner-secret-namespace: hpe-storage
  csi.storage.k8s.io/controller-publish-secret-name: 3par02
  csi.storage.k8s.io/controller-publish-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-stage-secret-name: 3par02
  csi.storage.k8s.io/node-stage-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-publish-secret-name: 3par02
  csi.storage.k8s.io/node-publish-secret-namespace: hpe-storage
  cpg: SSD_r6
  provisioning_type: tpvv
  accessProtocol: iscsi
  remoteCopyGroup: k8sRemoteCopyGroup
  replicationDevices: replicationdevices
allowVolumeExpansion: true
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: 3par-2
provisioner: csi.hpe.com
parameters:
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: 3par02
  csi.storage.k8s.io/provisioner-secret-namespace: hpe-storage
  csi.storage.k8s.io/controller-publish-secret-name: 3par02
  csi.storage.k8s.io/controller-publish-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-stage-secret-name: 3par02
  csi.storage.k8s.io/node-stage-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-publish-secret-name: 3par02
  csi.storage.k8s.io/node-publish-secret-namespace: hpe-storage
  cpg: SSD_r6
  provisioning_type: tpvv
  accessProtocol: iscsi
  remoteCopyGroup: k8sRemoteCopyGroup
  replicationDevices: replicationdevices
allowVolumeExpansion: true
reclaimPolicy: Delete
```

</p>
</details>

<details><summary>HPEReplicationDeviceInfo</summary>
<p>

```
apiVersion: storage.hpe.com/v1
kind: HPEReplicationDeviceInfo
metadata:
  name: replicationdevices
spec:
  target_array_details:
  - targetCpg: SSD_r6
    targetName: 3par01
    targetSecret: 3par01
    targetSecretNamespace: hpe-storage
  - targetCpg: SSD_r6
    targetName: 3par02
    targetSecret: 3par02
    targetSecretNamespace: hpe-storage
```

</p>
</details>

As you see, I use `reclaimPolicy: Delete` in my StorageClass. When pvc was created on 3par, it was created in 2 replicas (original and `.r*` on second 3par, due to replication policy). After deleting pvc, only replication volum was deleted, original volume still exists.

**Comment by datamattsson** [comment]
@wdurairaj please have a look at this too.

**Comment by wdurairaj** [comment]
Ideally the CR for the replicationdeviceinfo should contain only one secondary array details

```yaml
apiVersion: storage.hpe.com/v1
kind: HPEReplicationDeviceInfo
metadata:
  name: replicationdevices
spec:
  target_array_details:
  - targetCpg: SSD_r6
    targetName: 3par01
    targetSecret: 3par01
    targetSecretNamespace: hpe-storage
```

Above YAML definition means, the 3par01 is in replication (as secondary array) with the array mentioned in the primary secret of the storage class 3par02 (primary array).. 

Please correct this definition and see , if it works, or you can comment on this bug, and open a support case, we will have a deeper look.
